#!/bin/bash

DEFAULT_SPEED=1000
interface=$(ip -o -4 addr show up | awk '!/ lo / {print $2; exit}')
speed_file="/sys/class/net/$interface/speed"
speed=$(cat "$speed_file" 2>/dev/null)

if [ -n "$speed" ]; then
    echo -n "(${speed} Mbps)"
    echo
    if [ "$speed" -lt "$DEFAULT_SPEED" ]; then
        echo "#FFA500"  # Orange if degraded
    else
        echo "#00FF00"  # Green
    fi
else
    echo -n "(unknown speed)"
    echo
    echo "#AAAAAA"  # Gray if unknown
fi

